"""Shared-passphrase gate for the whole app.

One passphrase, shared by everyone with access to the deployment — not
per-user accounts. Only its SHA-256 hash is ever stored (in
`.streamlit/secrets.toml`, gitignored — see `.streamlit/secrets.toml.example`)
or compared; the plaintext passphrase itself is never persisted anywhere,
including in `st.session_state` beyond the single rerun that checks it.
See README's "Access control" section for what this is (and isn't) meant to
protect against.
"""
from __future__ import annotations

import hashlib
import hmac

__all__ = ["hash_passphrase", "verify_passphrase"]


def hash_passphrase(passphrase: str) -> str:
    """SHA-256 hex digest of `passphrase` — exactly the command shown in
    .streamlit/secrets.toml.example, so a hash generated by hand there is
    directly comparable to this function's output."""
    return hashlib.sha256(passphrase.encode("utf-8")).hexdigest()


def verify_passphrase(passphrase: str, expected_hash: str) -> bool:
    """True iff `passphrase` hashes to `expected_hash`. hmac.compare_digest
    isn't load-bearing for a local/trusted-network shared gate (there's no
    remote timing attack surface worth defending here), but it costs
    nothing over ==, so there's no reason not to use it."""
    return hmac.compare_digest(hash_passphrase(passphrase), expected_hash)
