"""Criteria V0 — the frozen scoring baseline.

DO NOT EDIT THIS FILE unless the user explicitly says "change criteria".

Every result produced by this platform is traceable to the criteria defined
here: base scores, priority multipliers, max-score ceilings, constraint
values and structure definitions. Editing them silently invalidates every
analysis that has already been run. See CLAUDE.md rule 2.

Implements docs/analysis_manual_th_v2.md §3.1–3.6. This file holds only
*data* — frozen dataclasses and MappingProxyType tables — never an
algorithm; engine/scoring.py is what reads a goal row and applies these
tables. That split matters for CLAUDE.md rule 2: fixing how scoring.py
*applies* these numbers is not "changing criteria" and needs no special
permission; changing a number in this file is.

Boundary convention: the manual gives explicit ≤/< symbols for the middle
(near-zero) bands of both scales, but only a bare dash ("5% – 10%") for
the upper OAR bands and the middle Target band's upper edge. Resolved so
every band is a non-overlapping, gap-free partition, matching the
convention the explicit bands already establish (a boundary value belongs
to whichever band's own written range states it as an endpoint, and the
single ">"/"≤-1%" bands are strict so they never double up with their
neighbor):
    OAR:    (10, ∞)->+3   [5,10]->+2   [2,5)->+1   (-2,2)->0   [-5,-2]->0   (-∞,-5)->-2
    Target: (2, ∞)->+3    [1,2]->+1.5  (-1,1)->0    (-∞,-1]->-2
This is why the task's boundary tests land where they do: x=10 -> +2 (not
+3, since ">10%" is strict), x=5 -> +2, x=2 -> +1, x=1 -> +1.5, x=-1 -> -2
(the Target penalty band is closed at -1).
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from types import MappingProxyType
from typing import Mapping, Optional

ENGINE_VERSION = "2.0"
CRITERIA_VERSION = "v0"

# --------------------------------------------------------------------------- #
# Categories (§3.1)
# --------------------------------------------------------------------------- #

CATEGORY_OAR = "OAR Sparing"
CATEGORY_TARGET = "Target Coverage"
CATEGORY_HOTSPOT = "Hot-spot Limit"

PRIORITY_LEVELS: tuple[int, ...] = (1, 2, 3)


# --------------------------------------------------------------------------- #
# Score bands (§3.2, §3.3)
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class ScoreBand:
    """One row of a base-score table: `base` applies when improvement %
    falls in (low, high), each bound inclusive iff its own flag is True.
    None on either side means unbounded that way."""

    label: str
    low: Optional[float]
    low_inclusive: bool
    high: Optional[float]
    high_inclusive: bool
    base: float

    def matches(self, pct: float) -> bool:
        if self.low is not None:
            if self.low_inclusive:
                if pct < self.low:
                    return False
            elif pct <= self.low:
                return False
        if self.high is not None:
            if self.high_inclusive:
                if pct > self.high:
                    return False
            elif pct >= self.high:
                return False
        return True


# §3.2 — OAR Sparing (also used for Hot-spot Limit, capped — see HOTSPOT_MAX_SCORE).
OAR_SCALE: tuple[ScoreBand, ...] = (
    ScoreBand("Excellent", 10.0, False, None, False, 3.0),
    ScoreBand("Moderate", 5.0, True, 10.0, True, 2.0),
    ScoreBand("Minor", 2.0, True, 5.0, False, 1.0),
    ScoreBand("Equivalent", -2.0, False, 2.0, False, 0.0),
    ScoreBand("Unspecified by protocol (fixed at 0)", -5.0, True, -2.0, True, 0.0),
    ScoreBand("Penalty", None, False, -5.0, False, -2.0),
)

# §3.3 — Target Coverage. The ≤ -1% penalty threshold is the platform's fixed
# reading of the protocol's ambiguous "decrease < 2%" wording (§3.3's own note).
TARGET_SCALE: tuple[ScoreBand, ...] = (
    ScoreBand("Excellent", 2.0, False, None, False, 3.0),
    ScoreBand("Minor", 1.0, True, 2.0, True, 1.5),
    ScoreBand("Equivalent", -1.0, False, 1.0, False, 0.0),
    ScoreBand("Penalty (fixed threshold)", None, False, -1.0, True, -2.0),
)

HOTSPOT_MAX_SCORE = 1.0  # a Hot-spot Limit's base score is min(oar_base, this)


def band_base_score(pct: float, bands: tuple[ScoreBand, ...]) -> float:
    for band in bands:
        if band.matches(pct):
            return band.base
    raise ValueError(f"No score band matches improvement % = {pct!r}")  # pragma: no cover


# --------------------------------------------------------------------------- #
# Priority multipliers (§3.2, §3.3)
# --------------------------------------------------------------------------- #

OAR_HOTSPOT_MULTIPLIER: Mapping[int, float] = MappingProxyType({1: 3.0, 2: 2.0, 3: 1.0})
TARGET_MULTIPLIER: Mapping[int, float] = MappingProxyType({1: 5.0, 2: 3.0, 3: 1.0})


# --------------------------------------------------------------------------- #
# Special-case goals (§3.4)
# --------------------------------------------------------------------------- #

# A "zero-limit" goal (e.g. V4725cGy <= 0.0%): AcceptanceLevel == 0, AtMost.
# The Improvement % formula is not used (Goal = 0 makes it undefined); scored
# directly, v3.0: Achieved == 0 -> +1, Achieved > 0 -> 0. Max base is 1, not 3
# — this specific goal type cannot mathematically reach the +3 tier.
ZERO_LIMIT_ACCEPTANCE_LEVEL = 0.0
ZERO_LIMIT_BASE_SCORE_MET = 1.0
ZERO_LIMIT_BASE_SCORE_NOT_MET = 0.0
ZERO_LIMIT_MAX_BASE = 1.0

# A "coverage-ceiling" goal (e.g. ITV45 V4275cGy >= 100%): a VolumeAtDose
# AtLeast goal whose required coverage is already 100%, so Achieved can't
# realistically exceed Goal — this goal type cannot mathematically reach the
# +3 tier either (only DoseAtVolume/other AtLeast types use a raw dose as
# AcceptanceLevel, not a volume fraction, so this is gated to VolumeAtDose
# specifically; the ~1.0 check would otherwise misfire on those).
COVERAGE_CEILING_GOAL_TYPE = "VolumeAtDose"
COVERAGE_CEILING_ACCEPTANCE_LEVEL = 1.0
COVERAGE_CEILING_MAX_BASE = 0.0

DEFAULT_MAX_BASE = 3.0


# --------------------------------------------------------------------------- #
# Structure groups — §3.7's Radar Chart categories
# --------------------------------------------------------------------------- #

# roi (standardized) -> structure_group. "Target" is assigned separately in
# engine/scoring.py (any Target Coverage-category goal, regardless of roi);
# a roi with no entry here (BODY, Cauda Equina, Spinal Cord, a Hot-spot-on-
# target goal, ...) gets structure_group = None and is left out of the radar.
STRUCTURE_GROUPS: Mapping[str, str] = MappingProxyType({
    "Bladder": "Bladder",
    "Rectum": "Rectum",
    "Small Bowel": "Bowel",
    "Bowel Bag": "Bowel",
    "Sigmoid": "Bowel",
    "Duodenum": "Bowel",
    "Bone Marrow": "Marrow",
    "Femoral Head Lt": "Femoral hd",
    "Femoral Head Rt": "Femoral hd",
    "Kidney Lt": "Kidneys",
    "Kidney Rt": "Kidneys",
})
TARGET_STRUCTURE_GROUP = "Target"


# --------------------------------------------------------------------------- #
# Critical Alert (§3.6)
# --------------------------------------------------------------------------- #

CRITICAL_ALERT_ROI = "PTV"  # the main PTV only — PTV-N is a different, nodal roi
CRITICAL_ALERT_GOAL_TYPE = "VolumeAtDose"
# The same 95% figure serves two roles in the standard template: the dose
# level to query (95% of Rx) and the coverage threshold to require — see
# §3.6 step 2 and step 5.
CRITICAL_ALERT_COVERAGE_FRACTION = 0.95
CRITICAL_ALERT_DOSE_TOLERANCE_FRACTION = 0.01  # the "±1%" in step 2


# --------------------------------------------------------------------------- #
# CRITERIA_SHA256 — a tamper-evident fingerprint of every table above
# --------------------------------------------------------------------------- #


def _band_snapshot(bands: tuple[ScoreBand, ...]) -> list[dict]:
    return [dict(label=b.label, low=b.low, low_inclusive=b.low_inclusive,
                high=b.high, high_inclusive=b.high_inclusive, base=b.base)
           for b in bands]


def _criteria_snapshot() -> dict:
    return {
        "engine_version": ENGINE_VERSION,
        "criteria_version": CRITERIA_VERSION,
        "categories": {"oar": CATEGORY_OAR, "target": CATEGORY_TARGET, "hotspot": CATEGORY_HOTSPOT},
        "priority_levels": list(PRIORITY_LEVELS),
        "oar_scale": _band_snapshot(OAR_SCALE),
        "target_scale": _band_snapshot(TARGET_SCALE),
        "hotspot_max_score": HOTSPOT_MAX_SCORE,
        "oar_hotspot_multiplier": {str(k): v for k, v in OAR_HOTSPOT_MULTIPLIER.items()},
        "target_multiplier": {str(k): v for k, v in TARGET_MULTIPLIER.items()},
        "zero_limit": {
            "acceptance_level": ZERO_LIMIT_ACCEPTANCE_LEVEL,
            "base_score_met": ZERO_LIMIT_BASE_SCORE_MET,
            "base_score_not_met": ZERO_LIMIT_BASE_SCORE_NOT_MET,
            "max_base": ZERO_LIMIT_MAX_BASE,
        },
        "coverage_ceiling": {
            "goal_type": COVERAGE_CEILING_GOAL_TYPE,
            "acceptance_level": COVERAGE_CEILING_ACCEPTANCE_LEVEL,
            "max_base": COVERAGE_CEILING_MAX_BASE,
        },
        "default_max_base": DEFAULT_MAX_BASE,
        "structure_groups": dict(STRUCTURE_GROUPS),
        "target_structure_group": TARGET_STRUCTURE_GROUP,
        "critical_alert": {
            "roi": CRITICAL_ALERT_ROI,
            "goal_type": CRITICAL_ALERT_GOAL_TYPE,
            "coverage_fraction": CRITICAL_ALERT_COVERAGE_FRACTION,
            "dose_tolerance_fraction": CRITICAL_ALERT_DOSE_TOLERANCE_FRACTION,
        },
    }


def _canonical_json(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"))


CRITERIA_SHA256: str = hashlib.sha256(_canonical_json(_criteria_snapshot()).encode("utf-8")).hexdigest()
