"""Criteria V0 — the frozen scoring baseline.

DO NOT EDIT THIS FILE unless the user explicitly says "change criteria".

Every result produced by this platform is traceable to the criteria defined
here: base scores, priority multipliers, max-score ceilings, constraint values
and structure definitions. Editing them silently invalidates every analysis
that has already been run. See CLAUDE.md rule 2.

Not yet implemented.
"""
from __future__ import annotations
